### ISSUE TITLE
Validate bubble_point function

### ISSUE THREAD

**Issue by zship96** [Kyupii/CheToolbox#19]
Validate bubble_point in separations.py is correct against examples. Provide proof/code used to test.

**Comment by zship96** [comment]
On first pass, this is what I have determined.
Major Issues: Fails when given an example problem. There may be an issue with the way we are using functions from common.py

See test setup and return below:
![Chetoolbox bubble point 1](https://github.com/Kyupii/CheToolbox/assets/159869564/2ed44f90-304c-4cf4-b361-490178925965)

Minor Issues: Docstrings and function arguments may benefit from edits, hard to read when using.

Unless it would harm some of the functionality of this, I'd like to suggest a re-write for this function that simplifies it and takes advantage of the fact that we have scipy dependency and Antoine's equation is being used. We shouldn't necessarily need to use a linear estimation and error functions from common.

**Comment by Kyupii** [comment]
re-arranged variable assignment in common.py

bubble_point is working now.
